---
title: "EXSS327PS4"
author: "Liam Cune"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(corrplot)
library(Hmisc)
library(cluster)
library(factoextra)
library(tidyverse)
library(dplyr)
library(factoextra)
library(Metrics)
data <- read.csv("ProblemSet4Data.csv")
```

```{r}
summary(data$ENROLL)
summary(data$WPCTBB)
summary(data$REVENUEBB)
```

```{r}
data2 <- subset(data, select = c("ENROLL", "WPCTBB", "REVENUEBB"))
cormat <- rcorr(as.matrix(data2), type = "pearson")
View(cormat$r)
View(cormat$P)
```

```{r}
std_data <- scale(data2)
max(std_data[,1])
max(std_data[,2])
max(std_data[,3])
```

```{r}
data3 <- data.frame(data$SCHOOL, std_data)
```

```{r}
data4 <- data3[,-1]
rownames(data4) <- data3$data.SCHOOL
k <- kmeans(data4, centers = 3, nstart = 25)
fviz_cluster(k, data = data4)
```

Finding Eucidian Distances
```{r}
# Add the cluster assignments to the original dataframe
data4$Cluster <- k$cluster

# Calculate the cluster centroids
cluster_centroids <- k$centers

# Calculate the Euclidean distance from each data point to its corresponding cluster centroid
distances_to_centroids <- sqrt(rowSums((data4 - cluster_centroids[data4$Cluster, ])^2))

# Add the distances to the original dataframe
data4$DistanceToCentroid <- as.vector(distances_to_centroids)

# Print the updated dataframe with the distances to centroids
print(data4)

data4 %>% group_by(Cluster) %>% summarise(max(DistanceToCentroid), min(DistanceToCentroid))
```

Anova for clusters
```{r}
data4 %>% group_by(Cluster) %>% summarise(mean(DistanceToCentroid^2))
191.4884 / 69.63
191.4884 / 90.10
191.4884 / 8.78
```

Mean z-scores by cluster
```{r}
data4 %>% group_by(Cluster) %>% summarise(mean(ENROLL), mean(WPCTBB), mean(REVENUEBB))
```


